project_name: goo
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - mod_timestamp: '{{ .Timestamp }}'
    binary: 'bin/goo_{{ .Target }}'
    env:
      - CGO_ENABLED=0
    no_unique_dist_dir: true
    ldflags:
      - -X github.com/goo-app/cli/internal.Version={{ .Version }}
      - -X github.com/goo-app/cli/internal.Timestamp={{ .Timestamp }}
      - -X github.com/goo-app/cli/internal.Revision={{ .ShortCommit }}
      - -X github.com/goo-app/cli/internal.CoreRepoSlug=goo-app-manager/main
      - -X github.com/goo-app/cli/internal.ProjectRepoSlug=goo-app-manager/goo
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: binary
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*feat[(\\w)]*:+.*$'
      order: 0
    - title: Bugs Fixed
      regexp: '^.*(fix|bugfix)[(\\w)]*:+.*$'
      order: 1
    - title: Internal Changes
      regexp: '^.*chore[(\\w)]*:+.*$'
      order: 2
    - title: Dependencies
      regexp: '^.*deps[(\\w)]*:+.*$'
      order: 3
    - title: Others
      order: 999
  filters:
    exclude:
      - '^.*\[skip-log\].*$'
      - '^.*\[skiplog\].*$'
      - '^.*\[skip log\].*$'
      - '^.*\[log skip\].*$'
      - '^.*\[log-skip\].*$'
      - '^.*\[no-log\].*$'
      - '^.*\[no log\].*$'
announce:
  discord:
    enabled: true
    message_template: 'New Release **{{ .Tag }}** is out: {{ .ReleaseURL }}'
    author: 'Goo Releaser'
    icon_url: 'https://raw.githubusercontent.com/goo-app/cli/main/manifest/goo.png'
