name: Release Dispatcher
on: workflow_dispatch
jobs:
  release:
    name: Release Dispatcher
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Download SVU
        run: go install github.com/caarlos0/svu@latest
      - name: Create tag
        run: |
          git tag $(suv next)
          git push --tags
