on:
  push:
    paths-ignore:
      - ".github/funding.yml"
      - ".github/workflows/release.yml"
      - "completion/**"
      - "manifest/**"
      - "install.sh"
      - "install.ps1"
      - "README.md"
      - "schema.app.manifest.json"
      - "schema.repo.manifest.json"
  pull_request:
    paths-ignore:
      - ".github/funding.yml"
      - ".github/workflows/release.yml"
      - "completion/**"
      - "manifest/**"
      - "install.sh"
      - "install.ps1"
      - "README.md"
      - "schema.app.manifest.json"
      - "schema.repo.manifest.json"
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...



